### ISSUE TITLE
Matching cdsapi library with new CDS request

### ISSUE THREAD

**Issue by flor187** [CLIMAAX/HEAVY_RAINFALL#5]
After reading the documentation from cds and cdsapi I realized that there must be compatibility between them. I locally modified the file environment.yml at 'cdsapi=0.7.0' with 'cdsapi=0.7.3'. Then in the hazard script i put my key api for new CDS. All cells from this script work perfectly and download the data from EUROCORDEX. 
My sugestion is to update the cdsapi library from the 'environment.yml'  file.
Thank you!

**Comment by flor187** [comment]
Another problem I faced is with the risk script 'EXTREME_PRECIPITATION_Risk_Assessment_examples.ipynb'. At begin, I put my bbox (region) and in final all plots are from Catalonia region. Now I have all the necessary input data in this script because I was able to download and clip data on my region from previous hazard script. 
Please, after solving with cdsapi, look at the risk script, change the bbox (region) and tell me what you get!
Thank you!

**Comment by chpolste** [comment]
> After reading the documentation from cds and cdsapi I realized that there must be compatibility between them. I locally modified the file environment.yml at 'cdsapi=0.7.0' with 'cdsapi=0.7.3'. Then in the hazard script i put my key api for new CDS. All cells from this script work perfectly and download the data from EUROCORDEX. My sugestion is to update the cdsapi library from the 'environment.yml' file. Thank you!

Hello @flor187,

thank you for the suggestion! The 0.7.0 version of cdsapi was still working in our automated dataset tests, but you are right: the documentation states that at least 0.7.2 should be used. I have upgraded the cdsapi package to the latest 0.7.5 version across all CLIMAAX repositories and on the CLIMAAX JupyterHub.

**Comment by chpolste** [comment]
I've created a separate issue for the problem regarding the bbox and plotted region.

**Comment by flor187** [comment]
Thank you!
